// Methods
export const ADD_TASK = "ADD_TASK"
export const REMOVE_TASK = "REMOVE_TASK"
export const CHECK_TASK = "CHECK_TASK"
export const UNCHECK_TASK = "UNCHECK_TASK"

// Form actions
export const CHANGE_TASK_INPUT_VALUE = "CHANGE_TASK_INPUT_VALUE"

// Task subbers
export const TASKS_SUBSCRIPTION_READY = "TASKS_SUBSCRIPTION_READY"
export const TASKS_SUBSCRIPTION_CHANGED = "TASKS_SUBSCRIPTION_CHANGED"
